FROM dustynv/ros:humble-pytorch-l4t-r35.3.1

# Instalation python packages
RUN pip install ultralytics --no-deps
RUN pip install py-cpuinfo scipy seaborn tqdm thop transitions matplotlib dill pyrr shapely

# Instalation system dependencies
RUN apt-get update && apt-get install -y \
    guvcview \
    git \
    libssl-dev \
    libusb-1.0-0-dev \
    pkg-config \
    libgtk-3-dev \
    udev \
    libgl1-mesa-dev \
    libglu1-mesa-dev

# Delete current OpenCV version (if conflict)
RUN apt remove opencv-* -y

# Package instalation ROS2 Humble
RUN apt install -y \
    ros-humble-vision-opencv \
    ros-humble-tf2-ros \
    ros-humble-diagnostic-updater \
    ros-humble-realsense2-camera \
    ros-humble-image-geometry \
    ros-humble-vision-msgs \
    ros-humble-tf2-geometry-msgs \
    python3-colcon-common-extensions

# Adding udev rules for Intel RealSense
RUN curl -sSL https://raw.githubusercontent.com/IntelRealSense/librealsense/master/config/99-realsense-libusb.rules \
    -o /etc/udev/rules.d/99-realsense-libusb.rules

# workspace configuration
RUN mkdir -p /home/user/ws/src
WORKDIR /home/user/ws
