version: '3'

services:
  martian-mines:
    image: highflyers/martian-mines-jetson
    build: 
      dockerfile: Dockerfile-jetson
    runtime: nvidia
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - /home/hf/Documents/martian_mines_ros2:/home/user/ws/src/martian_mines_ros2
